M48
; DRILL file {KiCad 9.0.3} date 2025-07-27T17:26:02-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-27T17:26:02-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X182.355Y-144.247
X188.355Y-144.247
T2
X150.156Y-140.078
X175.15Y-140.078
M30
